export const GET_ALL_PHOTO_REQUEST = 'GET_ALL_PHOTO_REQUEST';
export const GET_ALL_PHOTO_SUCCESS = 'GET_ALL_PHOTO_SUCCESS';
export const GET_ALL_PHOTO_FAIL = 'GET_ALL_PHOTO_FAIL';

export const GET_PHOTO_BY_LABEL_REQUEST = 'GET_PHOTO_BY_LABEL_REQUEST';
export const GET_PHOTO_BY_LABEL_SUCCESS = 'GET_PHOTO_BY_LABEL_SUCCESS';
export const GET_PHOTO_BY_LABEL_FAIL = 'GET_PHOTO_BY_LABEL_FAIL';
