export const GET_ALL_PHOTO_REQUEST = 'GET_ALL_PHOTO_REQUEST';
export const GET_ALL_PHOTO_SUCCESS = 'GET_ALL_PHOTO_SUCCESS';
export const GET_ALL_PHOTO_FAIL = 'GET_ALL_PHOTO_FAIL';

export const GET_PHOTO_BY_LABEL_REQUEST = 'GET_PHOTO_BY_LABEL_REQUEST';
export const GET_PHOTO_BY_LABEL_SUCCESS = 'GET_PHOTO_BY_LABEL_SUCCESS';
export const GET_PHOTO_BY_LABEL_FAIL = 'GET_PHOTO_BY_LABEL_FAIL';

export const UPLOAD_PHOTO_BY_URL_REQUEST = 'UPLOAD_PHOTO_BY_URL_REQUEST';
export const UPLOAD_PHOTO_BY_URL_SUCCESS = 'UPLOAD_PHOTO_BY_URL_SUCCESS';
export const UPLOAD_PHOTO_BY_URL_FAIL = 'UPLOAD_PHOTO_BY_URL_FAIL';

export const DELETE_PHOTO_REQUEST = 'DELETE_PHOTO_REQUEST';
export const DELETE_PHOTO_SUCCESS = 'DELETE_PHOTO_SUCCESS';
export const DELETE_PHOTO_FAIL = 'DELETE_PHOTO_FAIL';
